### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ocean90** [Automattic/o2#105]
There is a [style-rtl.css](https://github.com/Automattic/o2/blob/master/css/rtl/style-rtl.css) file but the last update was on Aug 22 2014 22:44:14 (see file header). It's also [not enqueued](https://github.com/Automattic/o2/blob/9eb296ca504af1b81fa15adbd55f172ee5c83840/o2.php#L168).

To generate RTL files we can use [grunt-rtlcss](https://github.com/MohammadYounes/grunt-rtlcss).

Current example of a RTL site: https://ar.wordpress.org/team/

**Comment by pento** [comment]
Fixed by #111.
