### ISSUE TITLE
Tags: text that looks like a hashtag in code blocks and link text should not be added to a post

### ISSUE THREAD

**Issue by lancewillett** [Automattic/o2#112]
Currently o2 is zealous in grabbing all tags in `#hashtag` format and adding them as post tags in the standard "post" post type taxonomy.

I'm pretty sure — could be wrong — that the design intent was to ignore anything that could be used in a code snippet, link href or link text, or pre-formatted HTML.

Evidence here: https://github.com/Automattic/o2/blob/609e3f55535c111a1d415d4c94dea58742b0b88e/inc/tags.php#L277 — ignoring certain parent HTML tags.

This doesn't seem to be working, though. :/
#### Steps to repeat

Start a new post, and use post content such as:

```
This one is in a link: <a href="https://www.google.com/">#tag-google</a>.

This one is in a code block: <code>#tag-code-what</code>

This one is plain text: #tag-plain
```

Publish the post. Then look at the post tags added in (verify in wp-admin post editor screen).
#### What I expected

I'd expect only `#tag-plain` to be added to the post as a WordPress post tag.
#### What happened instead

All three items that are vaguely hashtag-looking are added as post tags.
#### Screenshots

<img width="1105" alt="screen shot 2016-10-13 at 14 25 09" src="https://cloud.githubusercontent.com/assets/66797/19367663/f212785e-9150-11e6-9cf4-6942e19d8184.png">

<img width="1104" alt="screen shot 2016-10-13 at 14 25 22" src="https://cloud.githubusercontent.com/assets/66797/19367662/f20fc050-9150-11e6-9150-bca92fefea29.png">

<img width="930" alt="screen shot 2016-10-13 at 14 25 30" src="https://cloud.githubusercontent.com/assets/66797/19367665/f2146c90-9150-11e6-8d21-1dc4170860bc.png">

<img width="941" alt="screen shot 2016-10-13 at 14 25 36" src="https://cloud.githubusercontent.com/assets/66797/19367664/f213ce70-9150-11e6-843a-906cbf7a52f1.png">

**Comment by lancewillett** [comment]
The same thing happens in comment text.

**Comment by hoverduck** [comment]
What does appear to work is if the tag is contained inside the `[code] ... [/code]` shortcode.  Those tags are _not_ added to the post

**Comment by pento** [comment]
Wow, that's been broken for a long time.

It's caused by the `htmlentities()` call [here](https://github.com/Automattic/o2/blob/609e3f55535c111a1d415d4c94dea58742b0b88e/inc/tags.php#L265), which is obviously incorrect in retrospect. :-)

It was originally added to avoid warnings that `DOMDocument` would raise on some HTML. I'm inclined to add `LIBXML_NOWARNING | LIBXML_NOERROR` to the `loadHTML()` call when `WP_DEBUG` is disabled. I don't recall the old behaviour causing data loss, just irrelevant messages.
