### ISSUE TITLE
P2-Breathe Menu Issue

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/o2#119]
Please redirect me to the appropriate space for this issue. I realize that the theme is a separate component (perhaps I should add this to the .com forums as well). 

On Safari on iOS (iOS 10.2), in portrait mode, the hamburger menu works on the main blog feed, where the O2 field is, but on other pages, the menu opens and then obscures the rest of the page, hiding the right hand side of the site. I'm seeing this on a self hosted site, but it should be noted that this is also occurring out on wordpress.com.

The following video shows the issue: in tab one I'm on a self hosted site running the newest version of o2 and P2-Breathe, and on the second tab, I'm running P2 Breathe on a wordpress.com site. The same issue exists on both platforms. 

http://www.screencast.com/t/nIsyxeoAHyqM

**Comment by georgestephanis** [comment]
I know @jasmussen was just looking at some responsive stuff on p2-breathe -- may be related?

**Comment by jasmussen** [comment]
I believe I have deployed a few fixes to this on wordpress.com — can you verify that it works as it should? If yes, then the changes should trickle down to github soon!

**Comment by mrjarbenne** [comment]
@jasmussen that looks amazing. I love the move of the menu over to the left. There's also now a fluidity to the opening of the menu that feels more natural as it shifts downward and opens.

I wasn't aware that p2-breathe was available on github. I had been pulling it from svn, or downloading it from geto2.com. Is there a repo you can point me to so I can test the changes on self-hosted?

Thanks

**Comment by jasmussen** [comment]
We should make sure all those locations are updated! Glad you like it.
