### ISSUE TITLE
Checklist Item Renders Code when Marked Complete

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/o2#123]
If there is nothing else in the post there is just a small '> added before the username: 

![2017-01-10_17-07-47](https://cloud.githubusercontent.com/assets/480667/21826931/720bda68-d757-11e6-81a2-b1a2c57b0ba9.png)

But if within that same post there is an oembed element that also needs to be rendered after the post is published (like a YouTube Video), it gets a bit messier:

![2017-01-10_17-00-04](https://cloud.githubusercontent.com/assets/480667/21827038/dfad6870-d757-11e6-8f8f-e1565312ea18.png)

**Comment by sirbrillig** [comment]
I just encountered this myself. The problem is [this line](https://github.com/Automattic/o2/blob/81f7ed8672e197174a8f91f475c18084fb3d968b/modules/checklists/load.php#L251) which tries to store the item content in a data attribute but doesn't strip html tags.
