### ISSUE TITLE
Can't edit tags from wp-admin: Bulk Edit, Quick Edit both fail

### ISSUE THREAD

**Issue by alphaomegahost** [Automattic/o2#13]
Warning: explode() expects parameter 2 to be string, array given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 298

Warning: array_merge(): Argument #2 is not an array in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 299

Warning: array_unique() expects parameter 1 to be array, null given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 308

Warning: explode() expects parameter 2 to be string, array given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 298

Warning: array_merge(): Argument #2 is not an array in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 299

Warning: array_unique() expects parameter 1 to be array, null given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 308

Warning: Invalid argument supplied for foreach() in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/terms-in-comments.php on line 61

Warning: explode() expects parameter 2 to be string, array given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 298

Warning: array_merge(): Argument #2 is not an array in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 299

Warning: array_unique() expects parameter 1 to be array, null given in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php on line 308

Warning: Invalid argument supplied for foreach() in /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/terms-in-comments.php on line 61

Warning: Cannot modify header information - headers already sent by (output started at /home/my-server/public_html/my-site.com/o2/wp-content/plugins/o2/inc/tags.php:298) in /home/my-server/public_html/my-site.com/o2/wp-admin/post.php on line 237

thanks for your support

**Comment by westonruter** [comment]
I have a fix for this already in #12.

**Comment by lancewillett** [comment]
I ran into this today — editing tags from bulk edit or "Quick Edit" in posts lists in wp-admin triggers the error.

**Comment by lancewillett** [comment]
Fix in #12 fixes the Quick Edit tag editing. Nice! 👍

I did notice that bulk edit doesn't work with that change, though.

1. Posts list, select one or more posts.
2. Edit the tags (notice the tag field is empty).
3. When you update, the tags haven't changed.
4. In addition, if a tag was added to P2 front-end form with `#` format — it'll now be gone from the post after the bulk edit.

**Comment by lancewillett** [comment]
Hmm — testing now with WP trunk latest, and Twenty Fifteen — I can't bulk edit tags there, either. :( So could be a WP bug and not related to P2 or the o2 plugin.

**Comment by lancewillett** [comment]
OK, I take that back—with o2 plugin deactivated, editing via Bulk Edit works just fine.
