### ISSUE TITLE
REST API publish removes tags (Gutenberg incompatibility)

### ISSUE THREAD

**Issue by aduth** [Automattic/o2#161]
When a draft post is published via the REST API while O2 is active, any tags which had been assigned are removed.

Video demo: https://cloudup.com/cdIU5xPUBfn

Suspected cause: 

Processing of tags occurs in the `transition_post_status` which may not be accounting for a publish occurring via REST API.

https://github.com/Automattic/o2/blob/3335bbe076b0fa8e4579427661ee84735134081a/inc/tags.php#L15

https://github.com/Automattic/o2/blob/3335bbe076b0fa8e4579427661ee84735134081a/inc/tags.php#L339

https://github.com/Automattic/o2/blob/3335bbe076b0fa8e4579427661ee84735134081a/inc/tags.php#L345-L356

**Comment by lancewillett** [comment]
CC @jblz as you've looked at this type of bug before.

**Comment by mcsf** [comment]
@lancewillett, @jblz: is this something you can take on?

**Comment by jblz** [comment]
@mcsf -- I think this should be solved by landing #162, though,  I haven't had time to fully test.

@mdawaffe -- that's just waiting on testing, correct?

**Comment by mdawaffe** [comment]
Just testing, yeah. I don't recall if I tried it on WP.com, WP.org, or where :)

If there's a better way to implement it, I'd be cool with it.
