### ISSUE TITLE
Intermittent error_log entry during polling

### ISSUE THREAD

**Issue by ebinnion** [Automattic/o2#2]
@allendav originally reported this.

These get logged to wp-admin error_log on self-hosted, possibly the result of trashing a comment?

`[05-Jun-2015 22:33:05 UTC] PHP Notice:  Trying to get property of non-object in /home4/davalent/public_html/oxygen/wp-content/plugins/o2/inc/read-api.php on line 52`

@allendav reported that this is highly intermittent and that he hasn't able to reproduce.

**Comment by lancewillett** [comment]
I can't repeat this in a local install with WP 4.5-alpha-35776-src with o2 plugin version 0.2 and P2 "Breath" version 1.0.
