### ISSUE TITLE
o2 and BuddyPress compatibility

### ISSUE THREAD

**Issue by steadwell** [Automattic/o2#20]
I've got a social site with BuddyPress/bbPress installed (single install) using the P2 Breathe theme, however, when I activate the o2 plugin, the BuddyPress pages no longer display content. If anybody has anything on this, please let me know. Perhaps BuddyPress/bbPress is not meant to be used in conjunction with o2?

The site <a target="_blank" href="http://social.stephendowell.com">here</a> has o2 unactivated. The site <a target="_blank" href="http://dev.stephendowell.com">here</a>, has o2 activated.

**Comment by mrjarbenne** [comment]
Can you expand on this? What incompatibilities are you seeing?

**Comment by mrjarbenne** [comment]
I think having BP and o2 together could confuse your users. The front end posting functionality is very similar to the activity stream in BP. On a BP Multisite network, I can certainly see some cool possibilities in having o2 as the default subsite theme, in cases where a subsite creates a bit more extensibility than the BP groups function.

**Comment by steadwell** [comment]
Thanks for the quick response, in fact, I was still updating my  original message when you responded.
With o2 activated, my BuddyPress pages (members, activity, groups) display the header only . The div class="o2-posts" has nothing in it.

**Comment by steadwell** [comment]
I think I'll just bypass BuddyPress and go with o2 standalone, at least for the time being. Thanks for your input mrjarbenne!

**Comment by mrjarbenne** [comment]
👍🏻
