### ISSUE TITLE
Hide comment threads by default

### ISSUE THREAD

**Issue by xyz82br** [Automattic/o2#200]
There's a way to hide comment threads by default on homepage?

Thanks in advanced at all

**Comment by xyz82br** [comment]
Thanks in advanced at all

**Comment by xyz82br** [comment]
Hello there!

Get it done.

I edited line 509 of the /o2.php file:
`$show_comments = true; (I switched to false)`

How could I do this with a php filter?

**Comment by mirka** [comment]
There's a `showCommentsInitially` option you can pass in via the `o2_options` filter.

```php
function hide_comments( $o2_options ) {
	if ( is_home() ) {
		$o2_options['options']['showCommentsInitially'] = false;
	}

	return $o2_options;
}

add_filter( 'o2_options', 'hide_comments' );
```

Something like that 🙂

**Comment by xyz82br** [comment]
Thank you!
