### ISSUE TITLE
o2 Live Posts and Comments widget displays drafts but should only display published

### ISSUE THREAD

**Issue by designsimply** [Automattic/o2#26]
Steps to reproduce:

1. Install the P2 Breathe theme
1. Install the O2 plugin
1. Add the "o2 Live Posts and Comments" widget to the sidebar
1. Start a draft and save
1. Preview the draft and check to see if the draft appears in the "o2 Live Posts and Comments" widget

<strong>Result:</strong> I can see my draft in the "o2 Live Posts and Comments" widget but I expected to only be able to see published posts there.

<img width="1280" alt="screen shot 2016-02-01 at mon feb 1 4 14 07 pm" src="https://cloud.githubusercontent.com/assets/1119271/12736228/4dc3faae-c903-11e5-869b-003d3b6f14e1.png">
<sup>Tested with WordPress 4.4.1, p2-breathe wpcom-1.0 r33686 ([source](https://wpcom-themes.svn.automattic.com/p2-breathe/)), o2 e42fecc ([source](https://github.com/Automattic/o2/tree/e42fecc1d3100f694d3c41de5635281d6085710d)) hosted at SiteGround using Chrome 47.0.2526.111 on Mac OS X 10.10.5</sup>

**Comment by lancewillett** [comment]
Nice find — this should only show published posts. At least, that's what I'd expect.
