### ISSUE TITLE
Posts are showing as blank on the front-end

### ISSUE THREAD

**Issue by lukecav** [Automattic/o2#42]
O2 with the P2 Breath theme seems to work fine on a local dev site. But there is some issue which O2 stops posts from being able to be viewed on the front-end. The posts render as being blank.

**Comment by mrjarbenne** [comment]
It's working fine on my set up. Have you investigated plugin conflicts by deactivating everything else? If it's working on your dev set up it must be a conflict on your production server causing the issue.

**Comment by lukecav** [comment]
Yep have tested it with the active theme being P2 Breath and the only active plugin is O2. So with the frontpage is set to just show the latest posts. The homepage and any of the posts show as being blank. If you disable the O2 plugin, then the frontpage shows correctly and you can view any of the posts.

**Comment by lukecav** [comment]
Have tried the same setup on two different sites, both have the same issue with O2 blocks posts from loading and showing as blank.

**Comment by lukecav** [comment]
![posts now showing with o2 inactive](https://cloud.githubusercontent.com/assets/5797332/15478930/b498aaac-20da-11e6-88b3-8d41695f321c.png)

**Comment by lukecav** [comment]
It was working okay on a local dev site using Vagrant and VVV. But not on production site.

**Comment by lukecav** [comment]
![posts vvv](https://cloud.githubusercontent.com/assets/5797332/15478979/0ccd9458-20db-11e6-9dfb-fe3b2d5ced27.png)

**Comment by mrjarbenne** [comment]
Odd. What about another theme, although it won't look right, it should still render. That will eliminate a conflict between O2 and Breathe

![image](https://cloud.githubusercontent.com/assets/480667/15479124/a7d06e56-20ec-11e6-93ce-c2b994d1772d.png)

**Comment by mrjarbenne** [comment]
Is your admin panel secure (SSL). Maybe it's a mixed content issue from O2 trying to render a secured editor on an insecure front end?

(Now I'm just wildly guessing) 

When you inspect the main blank page using your browser inspector, is anything listed where the blog posts should be?

**Comment by lukecav** [comment]
Still shows as blank using either TwentyFifteen or TwentySixteen as the active theme.

**Comment by lukecav** [comment]
Site is not being forced or set as HTTPS, so no mixed content issues.

**Comment by lukecav** [comment]
You can see 

<script class="o2-post-action-states-dict" type="application/json" style="display:none">{"reply":{"default":{"shortText":"Reply","title":"Reply","classes":[],"genericon":"genericon-reply"}},"scrolltocomments":{"default":{"shortText":"Scroll","title":"Scroll to comments","classes":[],"genericon":"genericon-downarrow"}},"edit":{"default":{"shortText":"Edit","title":"Edit","classes":[],"genericon":"genericon-edit"}},"trash":{"default":{"shortText":"Trash","title":"Trash","classes":[],"genericon":"genericon-trash"}},"shortlink":{"default":{"shortText":"Shortlink","title":"Shortlink","classes":[],"genericon":"genericon-link"}},"stickyposts":{"normal":{"shortText":"Stick post to home","title":"Stick post to home","classes":[],"genericon":"genericon-pinned","nextState":"sticky"},"sticky":{"shortText":"Unstick post from home","title":"Unstick post from home","classes":["sticky"],"genericon":"genericon-pinned","nextState":"normal"}},"resolvedposts":{"normal":{"name":"Normal","shortText":"To-do","title":"To-do","classes":["state-normal"],"genericon":"genericon-dot","nextState":"unresolved","default":true},"unresolved":{"name":"Unresolved","shortText":"Mark as done","title":"Mark as done","classes":["state-unresolved"],"genericon":"genericon-checkmark","nextState":"resolved"},"resolved":{"name":"Resolved","shortText":"Clear to-do","title":"Clear to-do","classes":["state-resolved"],"genericon":"genericon-close","nextState":"normal"}}}</script>

When you inspect where the blogs should be displayed.

**Comment by lukecav** [comment]
`<script class="o2-post-action-states-dict" type="application/json" style="display:none">{"reply":{"default":{"shortText":"Reply","title":"Reply","classes":[],"genericon":"genericon-reply"}},"scrolltocomments":{"default":{"shortText":"Scroll","title":"Scroll to comments","classes":[],"genericon":"genericon-downarrow"}},"edit":{"default":{"shortText":"Edit","title":"Edit","classes":[],"genericon":"genericon-edit"}},"trash":{"default":{"shortText":"Trash","title":"Trash","classes":[],"genericon":"genericon-trash"}},"shortlink":{"default":{"shortText":"Shortlink","title":"Shortlink","classes":[],"genericon":"genericon-link"}},"stickyposts":{"normal":{"shortText":"Stick post to home","title":"Stick post to home","classes":[],"genericon":"genericon-pinned","nextState":"sticky"},"sticky":{"shortText":"Unstick post from home","title":"Unstick post from home","classes":["sticky"],"genericon":"genericon-pinned","nextState":"normal"}},"resolvedposts":{"normal":{"name":"Normal","shortText":"To-do","title":"To-do","classes":["state-normal"],"genericon":"genericon-dot","nextState":"unresolved","default":true},"unresolved":{"name":"Unresolved","shortText":"Mark as done","title":"Mark as done","classes":["state-unresolved"],"genericon":"genericon-checkmark","nextState":"resolved"},"resolved":{"name":"Resolved","shortText":"Clear to-do","title":"Clear to-do","classes":["state-resolved"],"genericon":"genericon-close","nextState":"normal"}}}</script>`

**Comment by mrjarbenne** [comment]
Do you have Jetpack or Genericon'd active so the fonts fire?

**Comment by mrjarbenne** [comment]
I wonder where that 'style=display: none;' in the top line is coming from.

**Comment by lukecav** [comment]
Okay figured the issue, it was user role. So the user role that was displaying the home page front-end as being blank of post was Administrator. But if you login as a user with the user role of Author, then the site is fine.
