### ISSUE TITLE
Oembed seem broken

### ISSUE THREAD

**Issue by onigetoc** [Automattic/o2#51]
Oembed seem broken.
I did a link to a Wordpress blog and the embed is blank.
I did see the same error on the P2 demo.
https://onigetoc.wordpress.com/2016/07/27/test-link/

On P2
https://p2classicdemo.wordpress.com/2016/07/27/oembed-link-do-not-work-http-www-nouvelordremondial/

I can see that the iframe code html is in the Google inspector, but it do not appear on the page and on the Wall.

**Comment by onigetoc** [comment]
It look like that it's not working only on Chrome, i may have a chrome extension who block this iframe

**Comment by mrjarbenne** [comment]
It looks like you are experiencing a mixed content issue. You can't embed a non-secure resource (URL beginning with "http"), inside a site that is secured (https). Try changing the URL of the item you are trying to oembed to https. I think you'll find that it works.

**Comment by onigetoc** [comment]
Ok, thank you, i will check this.
