### ISSUE TITLE
Alway ask me to login to reply

### ISSUE THREAD

**Issue by onigetoc** [Automattic/o2#52]
I have a new O2 installation, it alway ask me to login to reply, i login, visit another page and it ask again to login.

Also, on many Wordpress website, if i go to wp-admin, it remember my login information with Chrome. 
But in wp-login, information are auto filled but the login is alway wrong.

**Comment by grafikat** [comment]
I have reproduced this issue

**Comment by mrjarbenne** [comment]
I can also reproduce some of this issue. Although I am logged into the site, the comment button is prompting me to log in first: 

![2016-08-03_22-17-03](https://cloud.githubusercontent.com/assets/480667/17388148/1f08835a-59c8-11e6-84ac-e62e853dd237.png)

This is a new issue I wasn't seeing previously, and may be a bug related to this change: 

https://github.com/Automattic/o2/commit/d71599cc7083d753d34b70ed9db9a454667f9662

**Comment by westonruter** [comment]
I am also experiencing this issue.

**Comment by onigetoc** [comment]
I do not why no body is talking about fixing this issue.
