### ISSUE TITLE
Can´t get to see my posts or the field and button to publish

### ISSUE THREAD

**Issue by alphaomegahost** [Automattic/o2#7]
I tried O2 in my server but I can´t get to see my posts or the field and button to publish things,  
thanks for the news and help , I followed the instructions step by step and have all the dependencies mentioned activated

**Comment by NailedIT** [comment]
Hi there,
Had the same problem, maybe you made the same mistake like me and uploaded the plugin with the folder name "o2-master". After I renamed the plugin folder to "o2" it worked for me :-)

**Comment by alphaomegahost** [comment]
Thanks NailidIT , yes, taht was the reason,  it works great!, thanks a lo for your help , best wishes, great app thanks automattic
