### ISSUE TITLE
Undefined Function Error: wpcom_o2_is_enabled

### ISSUE THREAD

**Issue by mrjarbenne** [Automattic/o2#73]
Just updated with some of the new pull requests in play (thanks to @ocean90 and @pento for the recent activity). Thought I would report an error appearing in my php logs.

> Call to undefined function wpcom_o2_is_enabled() in .../wp-content/plugins/o2/inc/xposts.php on line 101

**Comment by ocean90** [comment]
Source: https://github.com/Automattic/o2/blob/6e2b934c9c8308d9a2094b84257f02e2c143c3b8/inc/xposts.php#L101-L106

In 7349caf23fdbbc854985121f75d77ff53055b868 @pento added another `wpcom_o2_is_enabled()` call but it uses `function_exists()`. We should do the same for the others.

**Comment by pento** [comment]
Thanks for the bug report, @mrjarbenne! I'll get that fixed up shortly. :-)
