### ISSUE TITLE
Javascript error when user is deleted

### ISSUE THREAD

**Issue by jurajk** [Automattic/o2#9]
i wanted to change my username, so i created a new account, deleted the old one and attributed all content to the new one. the plugin failed with a javascript error.

```comment.js:378 Uncaught TypeError: Cannot read property 'length' of null```

```jsonifiedModel.isAnonymousAuthor = ( 0 === jsonifiedModel.userLogin.length ) && ( 0 === jsonifiedModel.noprivUserName.length );```

after changing user_id for my old comments in wp_comments table to my new user id, everything works again.

**Comment by lancewillett** [comment]
This should be fixed with 55ec1fc189de6392b2b7fb5ffc832a2113e4603c

**Comment by dharmist** [comment]
Hello. This bug was present in the latest commit that I've used on my website again. I applied the same change as in the fix mentioned above, so just FYI.
